#+TITLE: Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ~/.vmacs.d/init.el

* Table of Contents :toc:
- [[#info][Info]]
  - [[#colemake-strategy][Colemake Strategy]]
  - [[#todo][Todo]]
- [[#initial-setup][Initial setup]]
  - [[#guix-manifest][Guix Manifest]]
  - [[#set-paths][Set paths]]
  - [[#use-utf-8][Use utf-8]]
  - [[#make-tab-and-c-i-read-as-seperate-keys][Make tab and C-i read as seperate keys]]
  - [[#start-the-emacs-server][Start the emacs server]]
  - [[#core-packages][Core Packages]]
- [[#my-elisp][My Elisp]]
  - [[#config-file-macros][Config file macros]]
  - [[#interactive-functions][Interactive Functions]]
  - [[#variables][Variables]]
- [[#exwm][Exwm]]
  - [[#keybinds][Keybinds]]
  - [[#dmenu][Dmenu]]
- [[#general-config][General Config]]
  - [[#relative-line-numbers][Relative Line Numbers]]
  - [[#use-spaces][Use spaces]]
  - [[#buffer-behavior][Buffer behavior]]
  - [[#file-hooks][File hooks]]
  - [[#use-backup-folder][Use backup folder]]
  - [[#dont-use-lock-files][Don't use lock files]]
  - [[#global-keybinds][Global Keybinds]]
- [[#ui][UI]]
  - [[#theme][Theme]]
  - [[#font][Font]]
  - [[#modeline][Modeline]]
  - [[#tweaks][Tweaks]]
- [[#evil][Evil]]
  - [[#evil-1][Evil]]
  - [[#goggles][Goggles]]
  - [[#leader][Leader]]
  - [[#surround][Surround]]
  - [[#escape][Escape]]
  - [[#collection][Collection]]
- [[#prog-mode][Prog mode]]
  - [[#smartparens][Smartparens]]
  - [[#paran-matching][Paran matching]]
  - [[#rainbow-delimiters][Rainbow delimiters]]
  - [[#rainbow-mode][Rainbow Mode]]
  - [[#hl-todo][HL todo]]
  - [[#eldoc][Eldoc]]
  - [[#git-gutter][Git gutter]]
  - [[#oragami][Oragami]]
  - [[#fira-code-ligatures][Fira Code Ligatures]]
- [[#general-packages][General Packages]]
  - [[#auth-source-pass][Auth Source Pass]]
  - [[#all-the-icons][All the icons]]
  - [[#ivy][Ivy]]
  - [[#neotree][Neotree]]
  - [[#which-key][which-key]]
  - [[#avy][Avy]]
  - [[#visual-fill-column][Visual Fill column]]
  - [[#perspectives][Perspectives]]
  - [[#undo-tree][Undo Tree]]
  - [[#helpful][Helpful]]
  - [[#dashboard][Dashboard]]
- [[#org][Org]]
  - [[#setup][Setup]]
  - [[#keybinds-1][Keybinds]]
  - [[#additions][Additions]]
- [[#ide][IDE]]
  - [[#company][Company]]
  - [[#flycheck][Flycheck]]
  - [[#yasnippet][Yasnippet]]
  - [[#projectile][Projectile]]
  - [[#lsp][LSP]]
- [[#langs][Langs]]
  - [[#lisp][Lisp]]
  - [[#python][Python]]
  - [[#rust][Rust]]
  - [[#shell][Shell]]
  - [[#hoon][Hoon]]
  - [[#web][Web]]
  - [[#javascript][Javascript]]
  - [[#lua][Lua]]
  - [[#cc][C/C++]]
  - [[#haskell][Haskell]]
- [[#programs][Programs]]
  - [[#man][Man]]
  - [[#info-1][Info]]
  - [[#magit][Magit]]
  - [[#sbbs][Sbbs]]
  - [[#keepass][Keepass]]
  - [[#pdf-tools][Pdf tools]]
  - [[#pass][Pass]]
  - [[#mpc][Mpc]]
  - [[#guix][Guix]]
  - [[#weechat][Weechat]]
  - [[#tmux][Tmux]]
  - [[#elfeed][Elfeed]]
  - [[#eshell][Eshell]]
  - [[#vterm][Vterm]]
  - [[#mentor][Mentor]]
  - [[#pulse-mixer][Pulse Mixer]]
  - [[#docker][Docker]]

* Info
** Colemake Strategy
Use neio for movement.
- h gets i (insert)
- k gets o (open)
- j gets n (search)
- l gets e (word end)
 
I chose these based on my usage frequency and ease of use.

Keys like gj and gk that use movement key semantics should be swapped for colemak movement keys

h needs to replace i in text object otherwise I can't cast line up in visual mode.
** Todo
- More snipets
- More org mode
- Change the behavior of reference popup buffers.
*** Keybinding
- Get rid of =evil-leader= keybinds
- Better app keybinds strategy
**** Need to add
- [ ] Dired
- [ ] Flychecker
- [ ] Smartparens
  - Forward/Backward Slurp/Barf
- [ ] Neotree
- [ ] More convenient maps for frequently used commands
  - =C-x b=
  - Persp
* Initial setup
** Guix Manifest
Build with
#+BEGIN_SRC sh
  guix package -m "~/dotfiles/guix-manifests/emacs.scm" -p "~/.guix-extra-profiles/emacs/emacs"
#+END_SRC

Marking guile blocks as lisp instead of scheme so geiser will shutup.
#+BEGIN_SRC lisp :tangle ~/dotfiles/guix-manifests/emacs.scm :noweb yes
  ;; -*- geiser-scheme-implementation: guile -*-
  (specifications->manifest
   '("emacs"
     "libcanberra"
     "freetype"
     "fontconfig"
     "emacs-aio"
     "emacs-request"
     "emacs-package-lint"
     <<packages>>
     ))
#+END_SRC
** Set paths
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.vmacs.d/lisp/")
  (let ((default-directory "~/.vmacs.d/lisp/"))
    (normal-top-level-add-subdirs-to-load-path))

  (setq org-directory "~/org/")
#+END_SRC
** Use utf-8
#+BEGIN_SRC emacs-lisp
  (prefer-coding-system 'utf-8-unix)
  (setq coding-system-for-read 'utf-8)
  (setq coding-system-for-write 'utf-8)
#+END_SRC
** Make tab and C-i read as seperate keys
#+BEGIN_SRC emacs-lisp
  (define-key input-decode-map [?\C-i] [C-i])
#+END_SRC
** Start the emacs server
#+BEGIN_SRC emacs-lisp
  (server-start)
#+END_SRC
** Core Packages
Packages needed for this config
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-general"
  "emacs-diminish"
#+END_SRC
*** General
#+BEGIN_SRC emacs-lisp
  (require 'general)
#+END_SRC
*** Dimnish
#+BEGIN_SRC emacs-lisp
  (require 'diminish)
#+END_SRC
* My Elisp
** Config file macros
*** Modeify
#+BEGIN_SRC emacs-lisp
  (defun modeify (symbol)
    (intern (concat (symbol-name symbol) "-mode")))
#+END_SRC
*** Interactive lambda
#+BEGIN_SRC emacs-lisp
  (defmacro i-lambda (symbol)
    `(lambda () (interactive) ,symbol))
#+END_SRC
*** require-md
Require symbol, activate and diminish its mode at symbol-mode
#+BEGIN_SRC emacs-lisp
  (defmacro require-md (symbol)
    (let ((mode (modeify symbol)))
      `(progn (require ',symbol)
              (,mode 1)
              (diminish ',mode))))
#+END_SRC
*** require-d
Require symbol and diminish its mode
#+BEGIN_SRC emacs-lisp
  (defmacro require-d (symbol)
    (let ((mode (modeify symbol)))
      `(progn (require ',symbol)
              (diminish ',mode))))
#+END_SRC
*** csetq
Taken from https://with-emacs.com/posts/tutorials/almost-all-you-need-to-know-about-variables/
#+BEGIN_SRC emacs-lisp
  (defmacro csetq (sym val)
    `(funcall (or (get ',sym 'custom-set) 'set-default) ',sym ,val))
#+END_SRC
** Interactive Functions
**** Toggle Transparency
taken from emacs wiki
#+BEGIN_SRC emacs-lisp
  (defun ne/toggle-transparency ()
    (interactive)
    (let ((alpha (frame-parameter nil 'alpha)))
      (set-frame-parameter
       nil 'alpha
       (if (eql (cond ((numberp alpha) alpha)
                      ((numberp (cdr alpha)) (cdr alpha))
                      ;; Also handle undocumented (<active> <inactive>) form.
                      ((numberp (cadr alpha)) (cadr alpha)))
                100)
           `(,alpha-focused . ,alpha-unfocused) '(100 . 100)))))
#+END_SRC
**** Centered mode
#+BEGIN_SRC emacs-lisp
  (setq ne/visual-center-mode-width 100)
  (define-minor-mode ne/visual-center-mode
    "Use `visual-fill-mode' to center text"
    :init-value nil :lighter nil :global nil
    (if ne/visual-center-mode
        (progn 
          (setq visual-fill-column-width ne/visual-center-mode-width)
          (setq visual-fill-column-center-text t)
          (visual-fill-column-mode 1))
      (progn
        (setq visual-fill-column-width nil)
        (setq visual-fill-column-center-text nil)
        (visual-fill-column-mode 0))))

  (defun ne/visual-center (&optional ARG)
    (interactive)
    (if visual-fill-column-mode 
        (visual-fill-column-mode 0)
      (progn 
        (setq visual-fill-column-width 150)
        (setq visual-fill-column-center-text t)
        (visual-fill-column-mode 1))))
#+END_SRC
**** Guix channel automation
- TODO: Make it work for non-git sources
#+BEGIN_SRC emacs-lisp
  (defun ne/sexp-pair-regex (name)
    (concat "(" name "[[:space:]\n\r]*\"\\(.*\\)\")"))

  (defun ne/git-hash (url commit)
    (let* ((odir (cadr (split-string (pwd))))
           (dir (file-name-sans-extension (car (last (split-string url "/"))))))
      (delete-directory dir t)
      (shell-command (concat "git clone " url))
      (cd dir)
      (shell-command (concat "git checkout -q " commit))
      (prog1
          (string-trim-right (shell-command-to-string "guix hash -rx ."))
        (delete-directory dir t)
        (cd odir))))

  (defun ne/guix-hash-at-point ()
    (interactive)
    (save-excursion
      (save-match-data
        (narrow-to-defun)
        (goto-char (point-min))
        (re-search-forward (ne/sexp-pair-regex "url"))
        (goto-char (point-min))
        (let ((url (match-string 1)))
          (re-search-forward (ne/sexp-pair-regex "commit"))
          (let* ((commit (match-string 1))
                 (hash (ne/git-hash url commit)))
            (re-search-forward (ne/sexp-pair-regex "base32"))
            (replace-match hash t nil nil 1)))
        (widen))))

  (defun ne/guix-bump-at-point (commit)
    (interactive "sCommit: ")
    (save-excursion
      (save-match-data
        (narrow-to-defun)
        (goto-char (point-min))

        (re-search-forward (ne/sexp-pair-regex "version"))
        (re-search-backward "\\.\\(.*\\)\"")
        (let ((new-version (number-to-string (1+ (string-to-number (match-string 1))))))
          (replace-match new-version t nil nil 1))

        (re-search-forward (ne/sexp-pair-regex "commit"))
        (replace-match commit t nil nil 1)

        (ne/guix-hash-at-point)
        (widen))))

  (defun ne/guix-bump-current-project ()
    (interactive)
    (let ((name (projectile-project-name))
          (commit (replace-regexp-in-string "\n\\'" "" 
                                            (shell-command-to-string "git rev-parse HEAD"))))
      (shell-command "git rev-parse HEAD")
      (with-current-buffer (find-file "/home/clone/projects/guix-channel/clone.scm")
        (save-excursion
          (goto-char (point-min))
          (search-forward (concat "define-public " name))
          (message "bCommit: %s" commit)
          (ne/guix-bump-at-point commit)
          (save-buffer)
          (magit-stage-file (magit-file-relative-name))
          (magit-commit-create (list (concat "-m Bumped " name)))
          (magit-push-current-to-pushremote)))))
#+END_SRC
** Variables
*** Solarized colors
#+BEGIN_SRC emacs-lisp
  (setq s_base03 "#002b36")
  (setq s_base02 "#073642")
  (setq s_base01 "#586e75")
  (setq s_base00 "#657b83")
  (setq s_base0 "#839496")
  (setq s_base1 "#93a1a1")
  (setq s_base2 "#eee8d5")
  (setq s_base3 "#fdf6e3")
  (setq s_yellow "#b58900")
  (setq s_orange "#cb4b16")
  (setq s_red "#dc322f")
  (setq s_magenta "#d33682")
  (setq s_violet "#6c71c4")
  (setq s_blue "#268bd2")
  (setq s_cyan "#2aa198")
  (setq s_green "#859900")
#+END_SRC
* Exwm
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-exwm"
  "emacs-dmenu"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ;; (require 'exwm)
  ;; (require 'exwm-config)
  ;; (exwm-config-default)
  ;; (general-define-key :keymaps 'override
  ;;                     "s-d" (i-lambda '(shell-command "firefox")))
#+END_SRC
** Keybinds
*** General
*** Shortcuts
** Dmenu
#+BEGIN_SRC emacs-lisp
  (require 'dmenu)
#+END_SRC
* General Config
** Relative Line Numbers
#+BEGIN_SRC emacs-lisp
  (setq display-line-numbers-type 'relative)
  (setq-default display-line-numbers-width 4)
  (dolist (mode '(prog-mode-hook
                  text-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 1))))
#+END_SRC
** Use spaces
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC
** Buffer behavior
#+BEGIN_SRC emacs-lisp
  (setq display-buffer-alist '(("^\\*Async Shell Command\\*$"
                                (display-buffer-reuse-window
                                 display-buffer-in-side-window)
                                (reusable-frames . visible)
                                (side . bottom))))
#+END_SRC
** File hooks
*** Helper
#+BEGIN_SRC emacs-lisp
  (defun save-hook-for-file (file cmd)
    (when (equal (buffer-file-name) file)
      (async-shell-command cmd)))
#+END_SRC
*** Hooks
** Use backup folder
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist '(("." . "~/.backup")))
#+END_SRC
** Don't use lock files
Lock files confuse npm start
#+BEGIN_SRC emacs-lisp
  (setq create-lockfiles nil)
#+END_SRC
** Global Keybinds
*** Switch tabs
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x <C-left>") 'tab-previous)
  (global-set-key (kbd "C-x <C-right>") 'tab-next)
#+END_SRC
* UI
** Theme
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-doom-themes"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (load-theme 'doom-solarized-dark t)
#+END_SRC
** Font
#+BEGIN_SRC emacs-lisp
  (setq frame-inhibit-implied-resize t)
  (set-face-attribute 'default nil :font "Fira Code" :height 90)
#+END_SRC
** Modeline
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-powerline"
  "emacs-airline-themes"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'powerline)
  (powerline-vim-theme)

  (require 'airline-themes)
  (setq airline-eshell-colors t)
  (load-theme 'airline-solarized t)
#+END_SRC
** Tweaks
*** Remove ui decorations
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (menu-bar-mode -1)            ; Disable the menu bar
#+END_SRC
*** Inhibit startup
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
#+END_SRC
*** Highlight current line
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook #'hl-line-mode)
#+END_SRC
*** Y or n
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
*** Transparancy
Taken from emacs wiki
#+BEGIN_SRC emacs-lisp
  (defvar alpha-focused 95)
  (defvar alpha-unfocused 90)
  (set-frame-parameter (selected-frame) 'alpha (cons alpha-focused
                                                     alpha-unfocused))
  (add-to-list 'default-frame-alist `(alpha . (,alpha-focused . ,alpha-unfocused)))
#+END_SRC
*** Disable tab bar buttons
#+BEGIN_SRC emacs-lisp
  (setq tab-bar-new-button-show nil)
  (setq tab-bar-close-button nil)
#+END_SRC
*** Don't blink the cursor
#+BEGIN_SRC emacs-lisp
  (blink-cursor-mode 0)
#+END_SRC
* Evil
*Guix Packages*
Don't enable evil in these modes
#+BEGIN_SRC emacs-lisp
  (setq evil-disabled-modes '())
#+END_SRC
** Evil
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (require-md evil)
  (dolist (mode evil-disabled-modes)
    (evil-set-initial-state (modeify mode) 'emacs))
#+END_SRC
*** Keybinds
Maybe this should be and evil-colemak layer
#+BEGIN_SRC emacs-lisp
  (general-define-key :states '(normal visual operator)
                      "n" nil
                      "N" nil
                      "e" nil
                      "i" nil
                      "o" nil
                      "O" nil)

  (general-define-key :states 'motion
                      "l" #'evil-forward-word-end
                      "L" #'evil-forward-WORD-end
                      "n" #'evil-backward-char
                      "N" #'evil-window-top
                      "e" #'evil-next-line
                      "i" #'evil-previous-line
                      "o" #'evil-forward-char
                      "O" #'evil-window-bottom
                      "TAB" nil
                      "<C-i>" #'evil-jump-forward)

  (general-define-key :states 'normal
                      "I" #'evil-lookup
                      "E" #'evil-join
                      "h" #'evil-insert
                      "H" #'evil-insert-line
                      "j" #'evil-search-next
                      "J" #'evil-search-previous
                      "k" #'evil-open-below
                      "K" #'evil-open-above)

  (general-define-key :states '(insert opertor visual replace)
                      "C-h" #'evil-normal-state)

  (general-define-key :states '(visual operator)
                      "h" evil-inner-text-objects-map)

  (general-define-key :states 'normal
                      :keymaps 'override
                      "gt" #'tab-bar-switch-to-next-tab
                      "gT" #'tab-bar-switch-to-prev-tab)

#+END_SRC
**** Window
#+BEGIN_SRC emacs-lisp
  (evil-collection-translate-key nil 'evil-window-map
    "n" "h"
    "e" "j"
    "i" "k"
    "o" "l"

    "h" "i"
    "j" "n"
    "k" "o"
    "l" "e"

    "N" "H"
    "E" "J"
    "I" "K"
    "O" "L"

    "H" "I"
    "J" "N"
    "K" "O"
    "L" "E")
#+END_SRC
** Goggles
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil-goggles"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'evil-goggles)
  (csetq evil-goggles-enable-delete nil)
  (csetq evil-goggles-enable-change nil)
  (evil-goggles-mode)
#+END_SRC
** Leader
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil-leader"
#+END_SRC

TODO: Just use general instead of bringing in evil-leader
#+BEGIN_SRC emacs-lisp :noweb yes
  (require 'evil-leader)
  (global-evil-leader-mode)
  (evil-leader/set-leader ",")
  (evil-leader/set-key
    "l" #'comment-region
    "u" #'uncomment-region
    "s" #'sp-forward-slurp-sexp
    "q" #'quote-word
    "rp" (i-lambda (async-shell-command "guix package -m /home/clone/dotfiles/guix-manifests/emacs.scm -p /home/clone/.guix-extra-profiles/emacs/emacs"))
    "tn" (i-lambda (switch-to-buffer-other-tab "*dashboard*"))
    "tc" #'tab-bar-close-tab
    "tm" #'tab-bar-move-tab
    "ts" #'tab-bar-switch-to-tab
    "w" #'surround-sexp
    "c" #'evil-ex-nohighlight
    ",t" #'ne/toggle-transparency
    "v" #'evil-window-vsplit
    "h" #'evil-window-split
    "av" #'vterm
    <<leader-key>>)
#+END_SRC
** Surround
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil-surround"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (global-evil-surround-mode)
#+END_SRC
** Escape
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil-escape"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-md evil-escape)
  (global-set-key (kbd "<escape>") 'evil-escape)
#+END_SRC
** Collection
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil-collection"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'evil-collection)

  (dolist (mode evil-disabled-modes)
    (delete mode evil-collection-mode-list))

  (defun my-hjkl-rotation (_mode mode-keymaps &rest _rest)
    (evil-collection-translate-key 'visual mode-keymaps
      "n" "h"
      "e" "j"
      "i" "k"
      "o" "l")

    (evil-collection-translate-key 'normal mode-keymaps
      "n" "h"
      "e" "j"
      "i" "k"
      "o" "l"

      "h" "i"
      "j" "n"
      "k" "o"
      "l" "e"

      "N" "H"
      "E" "J"
      "I" "K"
      "O" "L"

      "H" "I"
      "J" "N"
      "K" "O"
      "L" "E"

      "gn" "gh"
      "ge" "gj"
      "gi" "gk"
      "go" "gl"


      "gh" "gi"
      "gj" "gn"
      "gk" "go"
      "gl" "ge"
      ;;C-movement binds
      ))


  (add-hook 'evil-collection-setup-hook #'my-hjkl-rotation)
  (evil-collection-init)
#+END_SRC
* Prog mode
Prog mode enhancements.
** Smartparens
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-smartparens"
  "emacs-evil-smartparens"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-d smartparens)
  (require-d evil-smartparens)
  (require 'smartparens-config)

  (add-hook 'prog-mode-hook #'smartparens-mode)
  (add-hook 'smartparens-enabled-hook #'evil-smartparens-mode)
#+END_SRC
** Paran matching
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook #'show-paren-mode)
#+END_SRC
** Rainbow delimiters
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-rainbow-delimiters"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-d rainbow-delimiters)
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+END_SRC
** Rainbow Mode
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-rainbow-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'rainbow-mode)
  (dolist (mode-hook '(web-mode-hook css-mode-hook tide-mode-hook))
    (add-hook mode-hook #'rainbow-mode))
#+END_SRC
** HL todo
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-hl-todo"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'hl-todo)
  (global-hl-todo-mode 1)
#+END_SRC

Taken from DOOM emacs
#+BEGIN_SRC emacs-lisp
  (setq hl-todo-highlight-punctuation ":")
  (setq hl-todo-keyword-faces 
        `(("TODO" warning bold)
          ("FIXME" error bold)
          ("HACK" font-lock-constant-face bold)
          ("REVIEW" font-lock-keyword-face bold)
          ("NOTE" success bold)
          ("DEPRECATED" font-lock-doc-face bold)
          ("BUG" error bold)
          ("XXX" font-lock-constant-face bold)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook #'show-paren-mode)
#+END_SRC
** Eldoc
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook #'eldoc-mode)
#+END_SRC
** Git gutter
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-git-gutter"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-d git-gutter)
  (global-git-gutter-mode +1)
#+END_SRC
** Oragami
Code Folding
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-origami-el"
#+END_SRC
  
#+BEGIN_SRC emacs-lisp
  (require 'origami)
  (add-hook 'prog-mode-hook #'origami-mode)
#+END_SRC

Fold =aio-defun=
#+BEGIN_SRC emacs-lisp
  (defun origami-elisp-parser (create)
    (origami-lisp-parser create "(\\(aio-\\)?def\\w*\\s-*\\(\\s_\\|\\w\\|[:?!]\\)*\\([ \\t]*(.*?)\\)?"))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "f" #'origami-toggle-node
  "F" #'origami-recursively-toggle-node
#+END_SRC
** Fira Code Ligatures
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-fira-code-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'fira-code-mode)
  (add-hook 'prog-mode-hook #'fira-code-mode)

  (add-to-list 'fira-code-mode-disabled-ligatures "x")
#+END_SRC
* General Packages
Packages that extend emacs.
** Auth Source Pass
I have no idea why this is here
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-auth-source-pass"
#+END_SRC
** All the icons
Needed for doom-modeline and dashboard
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-all-the-icons"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'all-the-icons)
#+END_SRC
** Ivy
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-counsel" ;; Contains ivy
  "emacs-ivy-rich"
  "emacs-ivy-pass"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-md ivy)

  (setq ivy-use-virtual-buffers t)
  (require-md counsel)
  (setcdr (assq 'counsel-M-x ivy-initial-inputs-alist) "")

  (general-define-key :map 'ivy-mode-map
                      "C-x b" #'persp-ivy-switch-buffer)
#+END_SRC
*** Ivy addons
**** Ivy rich
#+BEGIN_SRC emacs-lisp
  (require-md ivy-rich)
#+END_SRC
** Neotree
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-neotree"
#+END_SRC

TODO: keybindings
#+BEGIN_SRC emacs-lisp
  (require 'neotree)
  (setq neo-theme (if (display-graphic-p) 'icons 'arrow))
  (setq neo-autorefresh nil)
  (add-hook 'neo-after-create-hook
            (lambda (_) (display-line-numbers-mode 0)))
#+END_SRC
#+BEGIN_SRC emacs-lisp
  (defun ne/neotree-refresh-toggle ()
    (interactive)
    (if (neo-global--window-exists-p)
        (neotree-hide)
      (progn 
        (neotree-show)
        (neotree-refresh))))

  (setq _last_neo_dir nil)
  (defun ne/neotree-show-project ()
    (interactive)
    (let ((proot (projectile-project-root)))
      (if (and (neo-global--window-exists-p) (string= _last_neo_dir proot))
          (neotree-hide)
        (progn 
          (setq _last_neo_dir proot)
          (neotree-dir proot)))))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "n" #'ne/neotree-show-project
#+END_SRC
** which-key
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-which-key"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-md which-key)
  (setq which-key-idle-delay 1.5)
#+END_SRC
** Avy
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-avy"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'avy)
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "m" #'evil-avy-goto-char-2
#+END_SRC
** Visual Fill column
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-visual-fill-column"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'visual-fill-column)
  (setq visual-fill-column-width 150)
  (setq visual-fill-column-center-text t)
#+END_SRC
** Perspectives
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-perspective"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'perspective)
  (diminish 'persp-mode)
  (csetq persp-show-modestring nil)
  (persp-mode)
#+END_SRC

Share some buffers across all perspectives
#+BEGIN_SRC emacs-lisp
  (setq persp-shared-buffs '("*Messages*" "*Backtrace*" "emacs.org" "todo.org" "*dashboard*"))
  (add-hook 'persp-switch-hook
            (lambda ()
              (dolist (buff persp-shared-buffs) 
                (persp-add-buffer buff))))

  (add-hook 'persp-created-hook
            (lambda () (switch-to-buffer "*dashboard*")))
#+END_SRC
** Undo Tree
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-undo-tree"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'undo-tree)
  (global-undo-tree-mode)
#+END_SRC
** Helpful
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-helpful"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'helpful)

  (global-set-key (kbd "C-h f") #'helpful-callable)
  (global-set-key (kbd "C-h v") #'helpful-variable)
  (global-set-key (kbd "C-h k") #'helpful-key)
#+END_SRC
** Dashboard
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-dashboard"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'dashboard)
  (setq dashboard-banner-logo-title "Welcome to Emacs Dashboard")
  (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
  ;;(dashboard-setup-startup-hook)
  (setq dashboard-startup-banner "~/Pictures/emacs_banner.png")
#+END_SRC
Dashboard doesn't activate itself if emacs is started with command line arguments, and I pass args for chemacs,
So it must be manually activated
#+BEGIN_SRC emacs-lisp
  (add-hook 'after-init-hook (lambda ()
                               ;; Display useful lists of items
                               (dashboard-insert-startupify-lists)))
  (add-hook 'emacs-startup-hook '(lambda ()
                                   (switch-to-buffer dashboard-buffer-name)
                                   (goto-char (point-min))
                                   (redisplay)
                                   (run-hooks 'dashboard-after-initialize-hook)))
#+END_SRC
* Org
** Setup
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-org"
  "emacs-org-journal"
  ;; Temporary disable as it conflicts with company
  ;;"emacs-org-roam"
  "emacs-toc-org"
  "emacs-org-superstar"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'org)
  (add-hook 'org-mode-hook
            (lambda ()
              (org-indent-mode)
              (diminish 'org-indent-mode)
              (ne/visual-center-mode)))
  (add-to-list 'org-agenda-files "~/org/")
#+END_SRC

Tangle on save
#+BEGIN_SRC emacs-lisp
  (defun ne/org-babel-tangle-dont-ask ()
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle)))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'ne/org-babel-tangle-dont-ask
                                                'run-at-end 'only-in-org-mode)))
#+END_SRC
TOC
#+BEGIN_SRC emacs-lisp
  (require 'toc-org)
  (add-hook 'org-mode-hook 'toc-org-mode)
#+END_SRC

Super star
#+BEGIN_SRC emacs-lisp
  (require 'org-superstar)
  (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
  (setq org-superstar-leading-bullet " ")
#+END_SRC

Load babel languages
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (scheme . t)
     (python . t)))
#+END_SRC
** Keybinds
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-evil-org"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq evil-org-movement-bindings '((left . "n") (down . "e") (up . "i") (right . "o")))
  (require-d evil-org)
  (add-hook 'org-mode-hook 'evil-org-mode)
#+END_SRC

Start hook block
#+BEGIN_SRC emacs-lisp
  (add-hook 'evil-org-mode-hook (lambda ()
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (evil-org-set-key-theme '(navigation insert))
#+END_SRC

The keys must be defined in the hook or they will be overwritten by evil-mode. "gi" must be defined because evil mode was overwriting the motion.
Text objects are defined from scratch instead of setting them in the theme because I need to move from i to h.
Colemak fixes
#+BEGIN_SRC emacs-lisp
  (general-define-key :states 'normal :keymaps 'evil-org-mode-map
                      "gi" #'org-backward-element
                      "i" nil
                      "o" nil
                      "O" nil
                      "I" nil
                      "H" #'evil-org-insert-line
                      "k" #'evil-org-open-below
                      "K" #'evil-org-open-above)

#+END_SRC

Manually add text operaters because it's easier than rebinding them
#+BEGIN_SRC emacs-lisp
  (general-define-key :states '(operator visual) :keymaps 'evil-org-mode-map
                      "he" #'evil-org-inner-object
                      "hE" #'evil-org-inner-element
                      "hr" #'evil-org-inner-greater-element
                      "hR" #'evil-org-inner-subtree
                      "ae" #'evil-org-an-object
                      "aE" #'evil-org-an-element
                      "ar" #'evil-org-an-greater-element
                      "aR" #'evil-org-an-subtree)
#+END_SRC

Additions
#+BEGIN_SRC emacs-lisp
  (general-define-key :states 'normal :keymaps 'evil-org-mode-map
                      "X" #'org-toggle-checkbox)
#+END_SRC

End hook block
#+BEGIN_SRC emacs-lisp
  ))
#+END_SRC
** Additions
*** Anki editor
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-anki-editor"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'anki-editor)
#+END_SRC
* IDE
Packages to turn emacs into an ide
** Company
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-company"
#+END_SRC

#+begin_src emacs-lisp
  (setq company-idle-delay 0.0)
  (require-md company)
  (add-hook 'after-init-hook #'global-company-mode)
#+end_src
** Flycheck
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-flycheck"
#+END_SRC

#+begin_src emacs-lisp
  (require 'flycheck)
  ;;(global-flycheck-mode)
  (diminish 'flycheck-mode)
#+end_src
** Yasnippet
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-yasnippet"
  "emacs-yasnippet-snippets"
  "emacs-ivy-yasnippet"
#+END_SRC

#+begin_src emacs-lisp
  (require 'yasnippet)
  (require 'ivy-yasnippet)
  (diminish 'yas-minor-mode)
  (yas-global-mode 1)
#+end_src
enter insert mode on snippet insert
#+begin_src emacs-lisp
  (advice-add #'ivy-yasnippet :after #'evil-insert-state)
#+end_src

#+begin_src emacs-lisp :noweb-ref leader-key
  "i" #'ivy-yasnippet
#+end_SRC

Use guix snippets
#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'yasnippet
    (add-to-list 'yas-snippet-dirs "~/builds/guix/etc/snippets"))
#+END_SRC
** Projectile
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-projectile"
  "emacs-counsel-projectile"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require-md projectile)
  (require-md counsel-projectile)
#+END_SRC

Bind projectile commands to leader p
#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "p" #'projectile-command-map
#+END_SRC
** LSP
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-lsp-mode"
  "emacs-lsp-ui"
  "emacs-lsp-ivy"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'lsp-mode)
  ;;(require 'lsp-clients)
  ;; (custom-set-variables '(lsp-enable-snippet t))
  ;; (csetq lsp-enable-snippet t)

  (add-variable-watcher 'lsp-enable-snippet
                        (lambda (&rest r)
                          (message "Changed: %s" r)))
  (require-d lsp-ui)
  (add-hook 'lsp-mode-hook #'lsp-ui-mode)
  (add-hook 'prog-mode-hook #'eldoc-mode)

  (require 'lsp-ivy)
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "o" #'lsp-ui-imenu
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ;; (csetq lsp-ui-doc-enable nil)
  (csetq lsp-ui-doc-position 'bottom)
  (csetq lsp-ui-doc-include-signature t)
  (general-define-key :states 'normal :keymaps 'lsp-ui-mode-map
                      "gh" #'lsp-ui-doc-glance
                      "gd" #'lsp-ui-peek-find-definitions
                      "gr" #'lsp-ui-peek-find-references
                      "gs" (lambda () (interactive)
                             (evil-window-split)
                             (evil-window-down 1)
                             (lsp-ui-peek-find-definitions))
                      "gv" (lambda () (interactive)
                             (evil-window-vsplit)
                             (evil-window-right 1)
                             (lsp-ui-peek-find-definitions))
                      ;; "I" (lambda () (interactive)
                      ;;       (lsp-ui-doc-show)
                      ;;       (lsp-ui-doc-focus-frame))
                      "I" #'lsp-ui-doc-focus-frame)

  (defun ne/lsp-ui-doc-unfocus-hide ()
    (interactive)
    (lsp-ui-doc-unfocus-frame)
    (lsp-ui-doc-hide))

  (general-define-key :states 'normal :keymaps 'lsp-ui-doc-frame-mode-map
                      ;; "q" #'ne/lsp-ui-doc-unfocus-hide
                      ;; "<escape>" #'ne/lsp-ui-doc-unfocus-hide

                      "q" #'lsp-ui-doc-unfocus-frame
                      "<escape>" #'lsp-ui-doc-unfocus-frame)

  (general-define-key :keymaps 'lsp-ui-peek-mode-map
                      "n" #'lsp-ui-peek--select-prev-file
                      "e" #'lsp-ui-peek--select-next
                      "i" #'lsp-ui-peek--select-prev
                      "o" #'lsp-ui-peek--select-next-file
                      "k" #'lsp-ui-peek--goto-xref
                      "K" #'lsp-ui-peek--goto-xref-other-window)
#+END_SRC
* Langs
Language Support
TODO: defer loading
** Lisp
*** General
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-eros"
#+END_SRC
  
#+BEGIN_SRC emacs-lisp
  (require 'eros)
  (eros-mode 1)
#+END_SRC
*** Common Lisp
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-slime"
#+END_SRC
  
#+BEGIN_SRC emacs-lisp
  (require 'slime)
  (setq inferior-lisp-program "sbcl")
#+END_SRC
*** Scheme
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-geiser"
  "mit-scheme"
  "emacs-flycheck-guile"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'xscheme)
  (require 'geiser)
  (require 'flycheck-guile)
  (with-eval-after-load 'geiser-guile
    (add-to-list 'geiser-guile-load-path "~/.guix-profile/share/guile/site/3.0/")
    (add-to-list 'geiser-guile-load-path "~/builds/guix"))

#+END_SRC
*** Elisp
#+BEGIN_SRC emacs-lisp
  (general-define-key :modes 'normal :keymaps 'emacs-lisp-mode-map
                      "C-c C-j" #'imenu)
#+END_SRC
** Python
*Guix Packages*
#+BEGIN_SRC emacs-lisp :noweb-ref packages
  "python-language-server"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (add-hook 'python-mode-hook #'lsp)
#+END_SRC
** Rust
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-rust-mode"
  "emacs-flycheck-rust"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (autoload 'rust-mode "rust-mode" nil t)
  (add-hook 'rust-mode-hook #'lsp)
#+END_SRC
** Shell
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "shellcheck"
  "emacs-yaml-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'yaml-mode)
#+END_SRC
** Hoon
#+BEGIN_SRC emacs-lisp
  (require 'hoon-mode)
#+END_SRC
** Web
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-web-mode"
  "emacs-skewer-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'web-mode)
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))

  ;;(require 'skewer-mode)
  ;;(add-hook 'html-mode-hook 'skewer-html-mode)
#+END_SRC
** Javascript

#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-nodejs-repl"
  "emacs-rjsx-mode"
  "emacs-npm-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq js-indent-level 2)
#+END_SRC
*** Node repl
#+BEGIN_SRC emacs-lisp
  (require 'nodejs-repl)
  (general-define-key :states '(normal insert) :keymaps '(typescript-mode-map tide-mode-map)
                      "C-x C-e" #'nodejs-repl-send-last-expression)
#+END_SRC

*** [TJ]sx
#+BEGIN_SRC emacs-lisp

  (require 'rjsx-mode)
  (csetq js2-strict-missing-semi-warning nil)
  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . rjsx-mode))
  (add-to-list 'auto-mode-alist '("\\.ts\\'" . rjsx-mode))
  (add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))
  (add-hook 'rjsx-mode-hook #'lsp)
  ;;(add-hook 'rjsx-mode-hook #'setup-tide-mode)
#+END_SRC
*** NPM
#+BEGIN_SRC emacs-lisp
  (require 'npm-mode)
  (diminish 'npm-mode)
  (add-hook 'rjsx-mode-hook #'npm-mode)
#+END_SRC

** Lua
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-lua-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'lua-mode)
#+END_SRC
** C/C++
#+BEGIN_SRC emacs-lisp
  ;;(add-hook 'c++-mode-hook #'lsp)
#+END_SRC
*** Keybinds
#+BEGIN_SRC emacs-lisp
  (general-define-key :states 'normal :keymaps 'c-mode-map
                      "gr" #'xref-find-references
                      "gD" #'xref-find-definitions-other-window)
#+END_SRC
** Haskell
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-haskell-mode"
  "emacs-haskell-snippets"
  "emacs-flycheck-haskell"
#+END_SRC
#+BEGIN_SRC emacs-lisp
  (require 'haskell-mode)
#+END_SRC
* Programs
Packages that offer a self contained experience.
** Man
#+BEGIN_SRC emacs-lisp
  (evil-collection-define-key 'normal 'Man-mode-map
    "k" #'man-follow)
#+END_SRC
** Info
#+BEGIN_SRC emacs-lisp
  (add-hook 'Info-mode-hook #'ne/visual-center-mode)
#+END_SRC

Prevent info mode from overwriting movement
#+BEGIN_SRC emacs-lisp
  (general-define-key :keymaps 'Info-mode-map "e" nil "i" nil)
#+END_SRC
** Magit
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-magit"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'magit)
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "am" #'magit-status
#+END_SRC
*** Keybinds
Translate-key doesn't work on magit
Also want "l" to be log instead of ediff ("o")
#+BEGIN_SRC emacs-lisp
  (evil-collection-define-key 'normal 'magit-status-mode-map
    "n" #'magit-dispatch
    "e" #'magit-section-forward
    "i" #'magit-section-backward
    "o" #'magit-ediff-dwim

    "h" #'magit-gitignore
    "k" #'magit-reset-quickly
    "e" #'magit-section-forward
    "j" #'evil-search-next

    "gj" #'magit-jump-to-untracked

    "gn" #'magit-section-up
    "ge" #'magit-section-forward-sibling
    "gi" #'magit-section-backward-sibling)
#+END_SRC
** Sbbs
#+BEGIN_SRC emacs-lisp
  (require 'sbbs)
  (define-key sbbs-read-mode-map (kbd "C-u")
    '(lambda () (interactive)
       (let ((thread-buf (current-buffer)))
         (sbbs-browse sbbs--board t)
         (kill-buffer thread-buf))))
#+END_SRC
*** Keybinds
#+BEGIN_SRC emacs-lisp
  (general-define-key
   :states 'normal :keymaps 'sbbs-read-mode-map
   "r" 'sbbs-read-reply
   "E" 'sbbs-read-next
   "I" 'sbbs-read-previous
   "o" 'sbbs-show-replies
   "n" 'sbbs-show-pop
   "N" 'sbbs-show-all
   "u" (lambda () (interactive)
         (let ((thread-buf (current-buffer)))
           (sbbs-browse sbbs--board t)
           (kill-buffer thread-buf))))

  (general-define-key
   :states 'normal :keymaps 'sbbs-view-mode-map
   "k" 'sbbs-view-open
   "RET" 'sbbs-view-open
   "c" 'sbbs-view-compose)
#+END_SRC
** Keepass
#+BEGIN_SRC emacs-lisp
  (require 'keepass-mode)
#+END_SRC
** Pdf tools
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-pdf-tools"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'pdf-tools)
  (pdf-loader-install)
  (add-hook 'pdf-view-mode-hook #'pdf-view-midnight-minor-mode)
  ;;(add-hook 'pdf-view-mode-hook (lambda () (blink-cursor-mode -1)))
  ;;(add-hook 'pdf-view-mode-hook (lambda () (internal-show-cursor nil nil)))
#+END_SRC
** Pass
#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "app" 'ivy-pass
  "api" 'password-store-insert
  "apg" 'password-store-generate
#+END_SRC
** Mpc
#+BEGIN_SRC emacs-lisp
  (general-define-key :states 'normal :keymaps 'mpc-mode-map
                      "RET" #'mpc-select-toggle
                      "q" #'mpc-quit
                      "p" #'mpc-toggle-play
                      "k" #'mpc-play-at-point)
#+END_SRC
** Guix
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-guix" ;; Curently broken
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'guix)
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "ag" #'guix
#+END_SRC
** Weechat
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-weechat"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'weechat)
  ;; (defcustom weechat-color-list '(unspecified "black" "dark gray" "dark red" "red"
  ;;                                             "dark green" "light green" "brown"
  ;;                                             "yellow" "dark blue" "light blue"
  ;;                                             "dark magenta" "magenta" "dark cyan"
  ;;                                             "light cyan" "gray" "white")
  (setq weechat-color-list '("black" "black" "dim gray" "dark red" "red"
                             "dark green" "green" "brown"
                             "orange" "dark blue" "blue"
                             "dark magenta" "magenta" "dark cyan"
                             "royal blue" "dark gray" "gray"))

  (weechat-connect "localhost" 9000 "2dLToM3HVaEpGaNT")
  (setq weechat-color-list (list 'unspecified s_base03 s_base01 s_red s_red
                                 s_green s_green s_base1
                                 s_orange s_blue s_blue
                                 s_violet s_magenta s_base1
                                 s_blue s_base1 s_base0))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "awm" #'weechat-monitor-buffer
#+END_SRC
** Tmux
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-emamux"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'emamux)
#+END_SRC
** Elfeed
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-elfeed"
  "emacs-elfeed-org"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'elfeed)
  (require 'elfeed-org)
#+END_SRC
 
#+BEGIN_SRC emacs-lisp
  (add-hook 'elfeed-search-mode-hook #'ne/visual-center-mode)
  (add-hook 'elfeed-show-mode-hook #'ne/visual-center-mode)
  (setq rmh-elfeed-org-files (list "~/dotfiles/elfeed.org"))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (custom-set-variables
   '(elfeed-feeds
     '("http://feeds.arstechnica.com/arstechnica/index"
       "https://graymirror.substack.com/feed"
       "https://karthinks.com/index.xml" "https://ambrevar.xyz/atom.xml"
       "https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ")))
#+END_SRC
** Eshell
#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "ae" #'eshell
#+END_SRC
*** Prompt
Customize Prompt. Taken from airline-themes.el and modified (lambdas are cool, ok?).
#+BEGIN_SRC emacs-lisp
  (setq eshell-highlight-prompt t
        eshell-prompt-regexp "^ [^#λ]* [#λ] "
        eshell-prompt-function
        (lambda ()
          (concat
           (propertize
            " "
            'face `(:foreground ,(face-foreground 'airline-insert-outer)
                                :background ,(face-background 'airline-insert-outer)))

           (propertize
            (concat (char-to-string airline-utf-glyph-separator-left) " ")
            'face `(:foreground ,(face-background 'airline-insert-outer)
                                :background ,(face-background 'airline-insert-inner)))

           (if (eq airline-display-directory 'airline-directory-shortened)
               (propertize
                (concat (airline-shorten-directory (eshell/pwd) airline-shortened-directory-length) " ")
                'face `(:foreground ,(face-foreground 'airline-insert-inner)
                                    :background ,(face-background 'airline-insert-inner)))
             (propertize
              (concat (abbreviate-file-name (eshell/pwd)) " ")
              'face `(:foreground ,(face-foreground 'airline-insert-inner)
                                  :background ,(face-background 'airline-insert-inner))))

           (propertize
            (concat (char-to-string airline-utf-glyph-separator-left) " ")
            'face `(:foreground ,(face-background 'airline-insert-inner)
                                :background ,(face-background 'airline-insert-center)))

           (propertize
            (concat (airline-curr-dir-git-branch-string (eshell/pwd)) " ")
            'face `(:foreground ,(face-foreground 'airline-insert-center)
                                :background ,(face-background 'airline-insert-center)))

           (propertize
            (concat (char-to-string airline-utf-glyph-separator-left))
            'face `(:foreground ,(face-background 'airline-insert-center)))

           (propertize " λ" 'face `(:foreground "#cb4b16"))
           (propertize " " 'face `()))))
#+END_SRC

(with-current-buffer "elfeed.org"
(with-current-buffer (elfeed-org-export-opml)
(set-visited-file-name "~/.vmacs.d/opml")
(save-buffer)
(elfeed-load-opml "~/.vmacs.d/opml")))
*** Aliases
#+BEGIN_SRC emacs-lisp
  (defalias 'e 'find-file-other-window)
  (defalias 'clear 'eshell/clear-scrollback)
#+END_SRC
** Vterm
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "cmake"
  "make"
  "libvterm"
  "emacs-vterm"
#+END_SRC
Don't shadow escape
#+BEGIN_SRC emacs-lisp
  (general-define-key :states 'insert :keymaps 'vterm-mode-map
                      "<escape>" nil)
#+END_SRC
** Mentor
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-xml-rpc"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'mentor)
  (setq mentor-rtorrent-external-rpc "http://127.0.0.1:8880/RPC2")
#+END_SRC
** Pulse Mixer
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-pulseaudio-control"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'pulseaudio-control)
#+END_SRC
** Docker
*Guix Packages*
#+BEGIN_SRC lisp :noweb-ref packages
  "emacs-docker"
  "emacs-docker-tramp"
  "emacs-dockerfile-mode"
  "emacs-docker-compose-mode"
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'docker)
  (require 'docker-tramp)
  (require 'dockerfile-mode)
  (require 'docker-compose-mode)
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref leader-key
  "ad" #'docker
#+END_SRC 
