#load agnoster prompt
#fpath=("$HOME/.zprompts" "$fpath[@]")
export PATH="$PATH:$HOME/bin"
#autoload -Uz promptinit
#promptinit
#prompt agnoster
if [[ "$TERM" == "dumb" ]]; then
   unset zle_bracketed_paste
else
    #load agnoster prompt
    fpath=("$HOME/.zprompts" "$fpath[@]")
    autoload -Uz promptinit
    promptinit
    prompt agnoster
    autoload -Uz add-zsh-hook
fi

if [[ "$TERM" == "st-256color" ]]; then
    function precmd () {
        print -Pn -- '\e]2;%n:%~\a'
    }

    function preexec () {
        print -Pn -- '\e]2;%n:%~' && print -n -- "${(q)1}\a"
    }

    add-zsh-hook -Uz precmd precmd
    add-zsh-hook -Uz preexec preexec
fi

#source keybinds
. ~/.zkeybinds

export EDITOR=nvim
export XDG_CONFIG_HOME=~/.config

#Load aliases
. ~/dotfiles/aliases
#Reload this file
alias r=". ~/.zshrc"

#Add qmk tools to path
export PATH="$PATH:$HOME/qmk_firmware/bin"
export PATH="$PATH:$HOME/.emacs-doom.d/bin"
export PATH="$PATH:$HOME/.local/bin"
#Add rustup to path
export PATH="$PATH:$HOME/.cargo/bin"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

alias cc="gcc"
export CC="gcc"
#Loads rvm as a function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#Loads ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    eval "$(<"$XDG_RUNTIME_DIR/ssh-agent.env")" > /dev/null
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob correct
unsetopt beep
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/clone/.zshrc'

autoload -Uz compinit
compinit
if [ -e /home/clone/.nix-profile/etc/profile.d/nix.sh ]; then . /home/clone/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
export GUIX_PACKAGE_PATH="$HOME/guix-packages:$HOME/guix-packages/gems"
alias discord="flatpak run com.discordapp.Discord"

GUIX_PROFILE="/home/clone/.guix-profile"
. "$GUIX_PROFILE/etc/profile"

GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
for i in $GUIX_EXTRA_PROFILES/*; do
  profile=$i/$(basename "$i")
  if [ -f "$profile"/etc/profile ]; then
    GUIX_PROFILE="$profile"
    . "$GUIX_PROFILE"/etc/profile
  fi
  unset profile
done

# Local guix ruby gems
ruby_hash=$(readlink -f $(which ruby) | cut -d '/' -f 4)
ruby_ver="$(echo $ruby_hash | cut -d '-' -f 3 | cut -d '.' -f 1-2).0"
export GEM_HOME=$HOME/.gem/$ruby_hash/$ruby_ver
#export GEM_PATH="$GEM_PATH:$GEM_HOME:$HOME/.guix-extra-profiles/langs/langs/lib/ruby/gems/$ruby_ver/"
export GEM_PATH="$GEM_HOME"
export GEM_SPEC_CACHE=$HOME/.gem/$ruby_hash/specs
#export PATH="$PATH:$GEM_HOME/bin"
export PATH="$GEM_HOME/bin:$PATH"
